services:
  calibre-web:
    image: ${DOCKER_IMAGE:-crocodilestick/calibre-web-automated:latest}
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - HARDCOVER_TOKEN=${HARDCOVER_TOKEN:-}
    volumes:
      - ./config:/config
      - ./ingest:/cwa-book-ingest
      - ${LIBRARY_PATH:-./library}:/calibre-library
    ports:
      - 8083:8083
    restart: unless-stopped
